name: cad-token-3d
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.3
  - pythonocc-core=7.7.2
  - pip:
      - torch==2.2.1
      - torchvision==0.17.1
      - torchaudio==2.2.1
      - triton==2.2.0
      - scipy==1.13.1
      - scikit-learn==1.6.1
      - tqdm==4.67.1
      - PyYAML==6.0.2
      - regex
      - tokenizers==0.22.0
      - transformers==4.56.1
      - accelerate==1.10.1
      - safetensors==0.6.2
      - huggingface-hub==0.34.4
      - matplotlib==3.9.4
      - pandas==2.3.2
      - networkx==3.2.1
      - trimesh==4.1.8
      - open3d==0.19.0
      - plyfile==0.9
      - pyquaternion==0.9.9